// Build a diagnostic derivative; never edit the pinned MIT vendor files.
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
export function deriveGrid128(name,source){
 let out=source;
 const replace=(from,to)=>{if(out.split(from).length!==2)throw Error('Grid128 anchor changed: '+name+' '+from);out=out.replace(from,to);};
 if(name==='OceanFFT'){
  replace('export const FFT_SIZE = 256;','export const FFT_SIZE = 128;');
  replace('const LOG2N = 8;','const LOG2N = 7;');
  replace('\treturn r;','\treturn r >> 1u;');
  replace('count: 64 * C * 2','count: 16 * C * 2');
  replace('c * 64u + gy * 8u + gx','c * 16u + gy * 4u + gx');
  replace(', out8: level( tex, 8 )','');
  replace('workgroupSize: [ 8, 8, 1 ]','workgroupSize: [ 4, 4, 1 ]');
  replace('s5: array<vec4f, 64>','s5: array<vec4f, 16>');
  replace('s6: array<vec4f, 16>','s6: array<vec4f, 4>');
  replace('var<workgroup> s7: array<vec4f, 4>;\n','');
  replace('s5[ ly * 8u + lx ] = mipMid[ ( c * 64u + ly * 8u + lx )','s5[ ly * 4u + lx ] = mipMid[ ( c * 16u + ly * 4u + lx )');
  replace("reduce( 's5', 's6', 4, 6, t )","reduce( 's5', 's6', 2, 6, t )");
  replace("${ reduce( 's6', 's7', 2, 7, t ) }\n\tworkgroupBarrier();\n${ reduce( 's7', null, 1, 8, t ) }","${ reduce( 's6', null, 1, 7, t ) }");
 }
 if(name==='Breakers')replace('const texel = L / 256;','const texel = L / 128;');
 // These files live one directory below proof. Shared GPU/module identities
 // still resolve to the original vendor, including SurfFoam's shared texture.
 out=out.replace(/from '([^']+)'/g,(whole,spec)=>{
  if(spec==='./OceanFFT.js')return whole;
  return "from '"+path.posix.normalize('../../vendor/tidewater/src/ocean/'+spec)+"'";
 });
 return '// GENERATED by scripts/generate-grid128.mjs; diagnostic only.\n// Derived from Tidewater 4811ba48d795197de5621985f404e765c0b7c0ef.\n// MIT (c) 2026 DRG Software Solutions LLC; see ../../vendor/tidewater/LICENSE.\n'+out;
}
export const names=['OceanFFT','WaterSurface','UnderwaterLighting','Breakers'];
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url)){
 const dir=path.join(root,'proof/grid128');fs.mkdirSync(dir,{recursive:true});
 for(const name of names)fs.writeFileSync(path.join(dir,name+'.js'),deriveGrid128(name,fs.readFileSync(path.join(root,'vendor/tidewater/src/ocean',name+'.js'),'utf8')));
}
